# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 21:11
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0002_static_and_dynamic_peer_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="networklocation",
            name="last_available",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="networklocation",
            name="last_unavailable",
            field=models.DateTimeField(null=True),
        ),
    ]
