# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 00:58
from __future__ import unicode_literals

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0003_log_recent_connection_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networklocation",
            name="last_available",
            field=models.DateTimeField(
                default=datetime.datetime(1019, 12, 5, 0, 58, 49, 907230, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="networklocation",
            name="last_unavailable",
            field=models.DateTimeField(
                default=datetime.datetime(1019, 12, 5, 0, 58, 49, 907230, tzinfo=utc)
            ),
        ),
    ]
