# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 01:48
from __future__ import unicode_literals

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0004_auto_20191204_1858"),
    ]

    operations = [
        migrations.AddField(
            model_name="networklocation",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="networklocation",
            name="last_available",
            field=models.DateTimeField(
                default=datetime.datetime(1019, 12, 5, 1, 48, 22, 365420, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="networklocation",
            name="last_unavailable",
            field=models.DateTimeField(
                default=datetime.datetime(1019, 12, 5, 1, 48, 22, 365420, tzinfo=utc)
            ),
        ),
    ]
